env:
  browser: true
  commonjs: true
  es2020: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
rules: {}
globals:
  process: readonly
  __dirname: readonly
  describe: readonly
  beforeEach: readonly
  afterEach: readonly
  it: readonly
