language: node_js
node_js:
  - 'node'
os:
  - linux

addons:
  apt:
    packages:
    - sqlite3
    sources:
    - travis-ci/sqlite3

install:
  - npm install

script:
  - npm run lint
  - npm run cover

# Send coverage data to Coveralls
after_script: 'cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js'
