  
language: node_js
node_js:
  - "node"
os:
  - linux
  - osx

install:
- npm install

script:
- npm run coveralls

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"