  
language: node_js
node_js:
  - "node"

env:
  global:
    - COVERALLS_PARALLEL=true

notifications:
  webhooks: https://coveralls.io/webhook

after_script:
  - "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"