language: node_js

node_js:
  - 'node'

os:
  - linux

install:
  - npm install

after_success:
  - npm run lint
  - npm run cover

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
